### ISSUE TITLE
Ajouter plusieurs cibles

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/news#1]
Bonjour,

Il faudrait pouvoir ajouter plusieurs cible et des cibles plus diverses.

Actuellement on ne peux sélectionner qu'un seul profil.

Il faudrait pourvoir sélectionner plusieurs profils, entités, groupes ou utilisateurs.

Cordialement,
Jérémy

**Comment by orthagh** [comment]
Done in version 0.90-1.3
