### ISSUE TITLE
creation de news sans resultat

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/news#10]
Bonjour,

GLPI 0.91, a la creation d'une news rien ne s'enregistre malgré tous les paramètres complétés

rien en mode debug, pas de log

**Comment by orthagh** [comment]
Bonjour @satyan01 

Pouvez essayer de nouveau avec la version 0.90-1.3 qui va sortir dans quelques jours.
J'ai fait une grosse passe pour ajouter les manques et corriger les bugs.
Vous pouvez la récuperer en avance via le master : https://github.com/pluginsGLPI/news/archive/master.zip

**Comment by satyan01** [comment]
Bonjour,

pas de changement rien ne s'enregistre

**Comment by orthagh** [comment]
des erreurs php ou sql dans les fichiers de log ?

**Comment by orthagh** [comment]
Merci de tester de nouveau, beaucoup de commits ce matin!

**Comment by satyan01** [comment]
no button + anymore

**Comment by orthagh** [comment]
logout & login

**Comment by satyan01** [comment]
ok pour le bouton mais toujours le meme probleme rien ne s'enregistre

**Comment by orthagh** [comment]
étrange, pas d'erreurs dans le logs (ou en mode debug) ?

**Comment by satyan01** [comment]
2016-06-02 01:15:10 [896@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT \'AMC\' AS currentuser,
                        `glpi_tickets`.`id` AS `ITEM_0`,   `glpi_tickets`.`name` AS `ITEM_1`,
                        `glpi_tickets`.`id` AS `ITEM_1_id`,
                        `glpi_tickets`.`id` AS `ITEM_1_id`, `glpi_tickets`.`content` AS `ITEM_1_content`, `glpi_tickets`.`status` AS `ITEM_1_status`, `glpi_entities`.`completename` AS `ITEM_2`,  `glpi_tickets`.`date` AS `ITEM_3`,   GROUP_CONCAT(DISTINCT `glpi_users_647c2805c3795643b0f52f520e7cdb86`.`id` SEPARATOR \'$$##$$\')
                                       AS `ITEM_4`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`users_id`, \' \',
                                                        `glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`alternative_email`)
                                                        SEPARATOR \'$$##$$\') AS `ITEM_4_2`, 
                           `glpi_tickets`.`type` AS `ITEM_5`,  `glpi_tickets`.`status` AS `ITEM_6`,  `glpi_tickets`.`priority` AS `ITEM_7`,   GROUP_CONCAT(DISTINCT `glpi_users_c5e682856a6d6fe48b5aed8f8b238708`.`id` SEPARATOR \'$$##$$\')
                                       AS `ITEM_8`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`users_id`, \' \',
                                                        `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`alternative_email`)
                                                        SEPARATOR \'$$##$$\') AS `ITEM_8_2`, 
                            IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_suppliers_54b493b9140ea0c46d5e2442edf1b74e`.`name`, \'__NULL__\'),
                                               \'$#$\',`glpi_suppliers_54b493b9140ea0c46d5e2442edf1b74e`.`id`) SEPARATOR \'$$##$$\'),
                                               \'__NULL__$#$\')
                              AS `ITEM_9`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ticketvalidations`.`status`, \'__NULL__\'),
                                               \'$#$\',`glpi_ticketvalidations`.`id`) SEPARATOR \'$$##$$\'),
                                               \'__NULL__$#$\')
                              AS `ITEM_10`,
                  
                  `glpi_tickets`.`due_date` AS `ITEM_11`,  `glpi_tickets`.`status` AS `ITEM_11_status`, `glpi_tickets`.`content` AS `ITEM_12`,  `glpi_tickets`.`date_mod` AS `ITEM_13`,  `glpi_tickets`.`closedate` AS `ITEM_14`,   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_fields_incidentqualificationfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`name`, \'__NULL__\'),
                                               \'$#$\',`glpi_plugin_fields_incidentqualificationfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`id`) SEPARATOR \'$$##$$\'),
                                               \'__NULL__$#$\')
                              AS `ITEM_15`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_fields_consequencesfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`name`, \'__NULL__\'),
                                               \'$#$\',`glpi_plugin_fields_consequencesfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`id`) SEPARATOR \'$$##$$\'),
                                               \'__NULL__$#$\')
                              AS `ITEM_16`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`.`completename`, \'__NULL__\'),
                                               \'$#$\',`glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`.`id`) SEPARATOR \'$$##$$\'),
                                               \'__NULL__$#$\')
                              AS `ITEM_17`,
                  
                  `glpi_tickets`.`id` AS id  FROM `glpi_tickets`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id`
                                              ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_a900a61824c3906cc82f90407e525192`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`tickets_id`
                                                 AND `glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`type`
                                                                 = 1 )LEFT JOIN `glpi_users`  AS `glpi_users_647c2805c3795643b0f52f520e7cdb86`
                                          ON (`glpi_tickets_users_a900a61824c3906cc82f90407e525192`.`users_id` = `glpi_users_647c2805c3795643b0f52f520e7cdb86`.`id`
                                              ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`tickets_id`
                                                 AND `glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`type`
                                                                  = 2 )LEFT JOIN `glpi_users`  AS `glpi_users_c5e682856a6d6fe48b5aed8f8b238708`
                                          ON (`glpi_tickets_users_74690f2626744a37ace4c70dd87cea83`.`users_id` = `glpi_users_c5e682856a6d6fe48b5aed8f8b238708`.`id`
                                              ) LEFT JOIN `glpi_suppliers_tickets`  AS `glpi_suppliers_tickets_74690f2626744a37ace4c70dd87cea83`
                                             ON (`glpi_tickets`.`id` = `glpi_suppliers_tickets_74690f2626744a37ace4c70dd87cea83`.`tickets_id`
                                                 AND `glpi_suppliers_tickets_74690f2626744a37ace4c70dd87cea83`.`type`
                                                                  = 2 )LEFT JOIN `glpi_suppliers`  AS `glpi_suppliers_54b493b9140ea0c46d5e2442edf1b74e`
                                          ON (`glpi_suppliers_tickets_74690f2626744a37ace4c70dd87cea83`.`suppliers_id` = `glpi_suppliers_54b493b9140ea0c46d5e2442edf1b74e`.`id`
                                              ) LEFT JOIN `glpi_ticketvalidations` 
                                             ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`
                                                 ) LEFT JOIN `glpi_plugin_fields_ticketcustomfields` 
                                          ON (`glpi_tickets`.`id` = `glpi_plugin_fields_ticketcustomfields`.`items_id`
                                              AND `glpi_plugin_fields_ticketcustomfields`.`itemtype` = \'Ticket\'
                                              ) LEFT JOIN `glpi_plugin_fields_incidentqualificationfielddropdowns`  AS `glpi_plugin_fields_incidentqualificationfielddropdowns_52a94952e02a45f95208e5ff37ddf381`
                                          ON (`glpi_plugin_fields_ticketcustomfields`.`plugin_fields_incidentqualificationfielddropdowns_id` = `glpi_plugin_fields_incidentqualificationfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`id`
                                              )LEFT JOIN `glpi_plugin_fields_consequencesfielddropdowns`  AS `glpi_plugin_fields_consequencesfielddropdowns_52a94952e02a45f95208e5ff37ddf381`
                                          ON (`glpi_plugin_fields_ticketcustomfields`.`plugin_fields_consequencesfielddropdowns_id` = `glpi_plugin_fields_consequencesfielddropdowns_52a94952e02a45f95208e5ff37ddf381`.`id`
                                              ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_74690f2626744a37ace4c70dd87cea83`
                                             ON (`glpi_tickets`.`id` = `glpi_groups_tickets_74690f2626744a37ace4c70dd87cea83`.`tickets_id`
                                                 AND `glpi_groups_tickets_74690f2626744a37ace4c70dd87cea83`.`type`
                                                                  = 2 )LEFT JOIN `glpi_groups`  AS `glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`
                                          ON (`glpi_groups_tickets_74690f2626744a37ace4c70dd87cea83`.`groups_id` = `glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`.`id`
                                              ) WHERE  `glpi_tickets`.`is_deleted` = \'0\'  AND (    (`glpi_tickets`.`type` = \'1\') AND `glpi_tickets`.`status` IN (\'5\',\'6\')  AND (`glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`.`id` = \'59\')  AND (``.`id` = \'0\' OR ``.`id` IS NULL)  OR (`glpi_tickets`.`type` = \'1\') AND `glpi_tickets`.`status` IN (\'5\',\'6\')  AND (`glpi_groups_80a94b3f6bc6957c5f1fd062f3013524`.`id` = \'59\')  AND (``.`id` = \'0\' OR ``.`id` IS NULL) ) GROUP BY `glpi_tickets`.`id` ORDER BY ITEM_13 DESC 
  Error: Column 'id' in where clause is ambiguous
  Backtrace :
  inc\search.class.php:903                           
  inc\search.class.php:98                            Search::constructDatas()
  inc\search.class.php:81                            Search::showList()
  front\ticket.php:56                                Search::show()

**Comment by orthagh** [comment]
La date et heure ne correpondent pas à vos test (je pense) ni au plugin en question.

Pouvez vous ajouter un Toolbox::logDebug($_POST); à la ligne 31 du fichier glpi/plugins/news/front/alert.form.php et me retourner le résultat apparaissant dans le fichier glpi/files_logs/php_errors.log (il est préférable de le vider avant).

Merci d'avance.

**Comment by satyan01** [comment]
2016-06-02 13:46:41 [854@UNGSRVGVA118]
  From C:\inetpub\wwwroot\glpi\plugins\news\front\alert.form.php line 31
  Array
  (
      [entities_id] => 0
      [is_recursive] => 1
      [name] => Test
      [message] => &lt;p&gt;test&lt;/p&gt;
      [_date_start] => 2016-06-02 00:00
      [date_start] => 2016-06-02 00:00
      [_date_end] => 2016-06-03 00:00
      [date_end] => 2016-06-03 00:00
      [type] => 1
      [is_displayed_onlogin] => 1
      [add] => Add
  )
  
2016-06-02 13:46:41 [854@UNGSRVGVA118]
  From C:\inetpub\wwwroot\glpi\plugins\news\front\alert.form.php line 31
  Array
  (
  )

**Comment by orthagh** [comment]
Vous avez envoyé 2 fois le formulaire ?
C'est très étrange, il semblerait qu'il y ait une première requête avec toutes les données, puis une seconde sans.

**Comment by satyan01** [comment]
non une seule entrée et save

**Comment by Kahalisto** [comment]
Bonjour,
J'ai rencontré le même après une primo install du plugin.
avec comme message dans sql-errors.log

**Comment by satyan01** [comment]
je n'ai pas de table plugin news alert

**Comment by orthagh** [comment]
3dd7e0b pour le is_deleted

@satyan01, si la table glpi_plugin_news_alerts n'existe pas, c'est complétement anormal, je pense qu'une réinstallation du plugin s'impose

**Comment by satyan01** [comment]
malheureusement meme apres reinstallation pas de tables

**Comment by satyan01** [comment]
Avec le master de ce matin tout fonctionne, merci beaucoup pour l'update

**Comment by orthagh** [comment]
ok parfait. je ferme

**Comment by satyan01** [comment]
juste une chose, en self service si on clique sur la croix on ne peut pas reafficher l'alerte

**Comment by orthagh** [comment]
après avoir "caché" une alerte et après rafraîchissement de la page, un lien "vous avez des alertes cachées..." devrait apparaître (meme en self-service)

**Comment by satyan01** [comment]
tout a fait et le message est access denied

**Comment by orthagh** [comment]
Je ne réplique pas.
Mon accès est toujours ok (pas de message d'erreurs) depuis l'interface self-service.

**Comment by satyan01** [comment]
je peux cliquer sur la ligne et accéder a la news mais si je veux la faire se reafficher sur la page home je ne  peux pas

**Comment by orthagh** [comment]
Oui c'est normal, une fois cachée, elle ne peuvent pas être de retour sur l'écran d'index.
La page est la pour permettre une visualisation seulement
