### ISSUE TITLE
Installation impossible sur version 0.85.5

### ISSUE THREAD

**Issue by Rifman5** [pluginsGLPI/news#11]
Bonjour,
Je ne parviens pas à l'installer sur la version 0.85.5 de GLPI hors sur le site il est mit comme compatible : http://plugins.glpi-project.org/#/plugin/news

Est-ce que vous avez une idée?

D'avance merci.

**Comment by flegastelois** [comment]
Bonjour,

Quelle version avez-vous essayé d'installer ?

Avez-vous un quelconque message d'erreur qui apparaît ?

Bien cordialement,

**Comment by trasher** [comment]
Les informations demandées n'ont pas été fournies. Vous pouvez réouvrir le ticket avec les informations si le problème persiste.
