### ISSUE TITLE
La diffusion des messages ne prend pas en compte les heures et les minutes

### ISSUE THREAD

**Issue by Kahalisto** [pluginsGLPI/news#14]
Malgré le commit [https://github.com/pluginsGLPI/news/commit/80153899b98b63c3b0fb4bfbcea266604fa8c988](url)
les messages ne prennent pas en compte les heures et les minutes pour l'affichage.
Test fait sur une alerte démarrant le 03/06/2016 à 11h30 et se terminant le 03/06/2016 à 11h35.
Le message reste toujours affiché.

**Comment by orthagh** [comment]
Merci pour votre retour
