### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by keyser75000** [pluginsGLPI/news#15]
J'ai récupéré la master après correction du hook.php et du champ is_deleted.
L'installation se passe sans erreur
Après création d'une alerte, impossible de la voir dans la liste.
Dans le sql-error.log il y a l'erreur suivante :
`Error: Unknown column 'glpi_plugin_news_alerts.profiles_id' in 'on clause'`
Le champ profiles_id n'existe pas dans cette table. Pourtant il est dans la requête de création du hook.php. 

Si j'ajoute à la main le champ "profiles_id" dans la table (avec aussi une valeur par défaut), je peux de nouveau voir mes alertes créées.
Mais elles ne s'affichent pas sur la page de connexion.
J'ajoute que j'ai testé sur deux serveurs (qualif / pré-prod) qui n'avaient jamais eu ce plugin auparavant)

**Comment by orthagh** [comment]
Bonjour, pouvez préciser l'erreur entière avec son "backtrace".
Vous trouverez cela dans les fichiers : 
glpi/files/_log/[php,sql]-errors.log

Le champs profiles_id n'est plus censé exister et devrait être migré dans le nouveau système de cibles (glpi_plugin_news_alerts_targets), j'ai supprimé le restant dans le fichier hook.

**Comment by keyser75000** [comment]
Désolé, je n'avais pas la main ce week-end :)
Curieusement en relançant mon portail le message de vendredi s'est affiché. Surement un problème de cache sur le navigateur.
J'ai recréé une alerte et vérifier dans les tables. Les infos sont identiques et la nouvelle alerte ne s'affiche pas, même après redémarrage du navigateur.
L'erreur est la suivante :
`2016-06-06 09:40:08 [@xxxxxx]
*** MySQL query error:
SQL: INSERT
                   INTO 'glpi_profiles_users' ('entities_id','profiles_id','is_recursive','users_id','is_dynamic') VALUES (\'RF &amp;gt; 'GFI\',\'10\',\'0\',\'19\',\'1\')`
`Error: Incorrect integer value: 'RF &amp;gt; GFI' for column 'entities_id' at row 1`
`Backtrace :`
`inc/commondbtm.class.php:425`
`inc/commondbtm.class.php:831                       CommonDBTM->addToDB()`
`inc/user.class.php:986                             CommonDBTM->add()`
`inc/user.class.php:866                             User->applyRightRules()`
`inc/commondbtm.class.php:1144                      User->post_updateItem()`
`inc/auth.class.php:756                             CommonDBTM->update()`
`front/login.php:78                                 Auth->Login()`
Je note que les erreurs semblent s'afficher pour les sous-entités auxquelles j'appartiens (j'ai une erreur par sous-entité). L'erreur n'apparait pas pour mon entité racine.

**Comment by orthagh** [comment]
Cette dernière erreur ne semble pas relative au plugin news, mais plutôt du coeur de glpi (et plus particulièrement l'insertion des profils dynamiques depuis les règles d'habilitations)

Pouvez-vous désinstaller et réinstaller le plugin news pour essayer de faire remonter l'erreur précédente ?

**Comment by keyser75000** [comment]
J'ai désinstallé le plugin (effacement tables et répertoire dans /plugins).
_A noter (j'avais déjà remarqué mais je ne l'avais pas mentionné), la désinstallation via l'interface de plugins ne drop pas la table glpi_plugin_news_alerts_targets. J'ai dû le faire._

Réinstallation (0.90+1.3) :
- modification du champ 'is_deleted'.
- Je créé une alerte et la sauvegarde : OK
- En listant les alertes rien n'apparait.

Erreur :
`2016-06-06 10:38:20 [19@xxxxxxxx]`
  `*** MySQL query error:`
  `SQL: SELECT \'xxxxxx\' AS currentuser,
                        'glpi_plugin_news_alerts'.'entities_id', 'glpi_plugin_news_alerts'.'is_recursive',  'glpi_plugin_news_alerts'.'name' AS 'ITEM_0',
                        'glpi_plugin_news_alerts'.'id' AS 'ITEM_0_id',
                        'glpi_plugin_news_alerts'.'date_start' AS 'ITEM_1',  'glpi_plugin_news_alerts'.'date_end' AS 'ITEM_2',  'glpi_entities'.'completename' AS 'ITEM_3',  'glpi_plugin_news_alerts'.'is_recursive' AS 'ITEM_4',  'glpi_profiles'.'name' AS 'ITEM_5',  'glpi_plugin_news_alerts'.'id' AS id  FROM 'glpi_plugin_news_alerts'LEFT JOIN 'glpi_entities'
                                          ON ('glpi_plugin_news_alerts'.'entities_id' = 'glpi_entities'.'id'
                                              )LEFT JOIN 'glpi_profiles'
                                          ON ('glpi_plugin_news_alerts'.'profiles_id' = 'glpi_profiles'.'id'
                                              ) WHERE  'glpi_plugin_news_alerts'.'is_deleted' = \'0\'  ORDER BY ITEM_0 ASC  LIMIT 0, 15`
  `Error: Unknown column 'glpi_plugin_news_alerts.profiles_id' in 'on clause' `
  `Backtrace :`
  `inc/search.class.php:903`
   `inc/search.class.php:98                            Search::constructDatas()`
  `inc/search.class.php:81                            Search::showList()`
  `plugins/news/front/alert.php:33                    Search::show()`

En ajoutant le champ 'profiles_id' à la table glpi_plugin_newws_alerts, je vois mon alerte dans la liste.
Par défaut, l'alerte a 'Profils > Tous'. Mais l'alerte ne s'affiche pas.
Et là je retrouve l'erreur d'insert sur la table glpi_profiles_users. Cette erreur n'apparait que lorsque je manipule les alertes. Pas d'erreur dans d'autres utilisations de GLPI.

**Comment by orthagh** [comment]
bien vu pour la table glpi_plugin_news_alerts_targets, le commit du dessus devrait combler ce manque.

**Comment by orthagh** [comment]
Pour votre erreur, c'est lié à une colonne affichée lié au profile, je suis en train de préparer une correction, mais en attendant voici une requête sql qui devrait permettre de corriger votre instance : 

DELETE FROM `glpi_displaypreferences` WHERE `itemtype` LIKE '%PluginNews%

**Comment by keyser75000** [comment]
Cela corrige l'erreur du champ profiles_id dans le select ? C'est ça ?
Je retenterai une réinstallation complète avec cette correction dans la journée.

Sinon pour l'autre erreur je n'avais pas fait attention, mais la requête d'insert dans glpi_profiles_users tente d'insérer le nom de l'entité dans 'entities_id'.

**Comment by orthagh** [comment]
voila, le dernier master devrait maintenant être corrigé.

**Comment by orthagh** [comment]
Concernant votre autre erreur sur les entités, comme c'est non relatif au plugin news, je vous invite à : 
- Vérifier que vous avez la dernière version stable de glpi (actuellement 0.90.3)
- ouvrir un ticket sur le [forum communautaire](forum.glpi-project.org) ou sur [l'issue tracker](https://github.com/glpi-project/glpi/issues/) de glpi (en anglais)

**Comment by keyser75000** [comment]
Je viens de refaire une installation complète.
C'est parfait ça fonctionne. J'ai aussi testé la désinstallation.
