### ISSUE TITLE
Is it possible to display on a separate webpage

### ISSUE THREAD

**Issue by bacus99** [pluginsGLPI/news#18]
Hi,

Is it possible to display the alerts on an independant PHP page like the logging screen, but only the alerts?  (Not seen the logging screen)

Same usage as FROM TO time period over refresh

**Comment by orthagh** [comment]
Hello @bacus99 

Sorry for the long delay of this answer.
Yes you can retrieve news in a single page (aka without glpi header/footer).

Browse to plugins http://path/to/glpi/news/front/external.php

**Comment by Armin83** [comment]
Can you post your code as example ?

I would like to embedded this in our intranet - edv - support site where phone number / glpi-email / http web link to email is displayed i would like further text if alarm is active.

I don't know html so good and in Internet explorer i got error other firefox nothing ist displayed.

I try:
`<!DOCTYPE html>
<iframe id="Test" src="http://ticket01/glpi/plugins/news/front/external.php" style="width:100%;" frameborder="0">
</iframe>`

or 
`
<html>
<header>
</header>
<body>
<object type="text/html" data="http://ticket01/glpi/plugins/news/front/external.php" style="width:100%; height:100%">
<p>backup content</p>
</object>
</body>
</iframe>
</html>
`
