### ISSUE TITLE
date_start and date_end  not valid to start alert

### ISSUE THREAD

**Issue by guillermohaad** [pluginsGLPI/news#19]
Hi,
I have version 0.90.3 and update news of https://github.com/pluginsGLPI/news/
when I place start date and end date not valid to start alert. But if I do not put him these if you show the alert.

thank you

**Comment by flegastelois** [comment]
Hi,

I don't understand your message.
Can you give us further explanation ?

Regards,

**Comment by guillermohaad** [comment]
Hi, flegastelois

The plugin News does not validate the start date and end date. 
when the initial date arrives does not show the alert. But if you do not put dates if it shows

Deputy evidence.:

![image](https://cloud.githubusercontent.com/assets/12921805/17294471/b0dc026a-57bc-11e6-9e27-6872f691a605.png)

**Comment by vinz38500** [comment]
Hello
I've just tested with v9.1 and looks like if Dates are set, then nothing is displayed... Then for me this is more a bug than an enhancement.... With no Date defined, it displays an alert
![image](https://cloud.githubusercontent.com/assets/20357060/18826183/61ee980c-83cc-11e6-9f24-c03c7d5164cf.png)

**Comment by guillermohaad** [comment]
Thank you friend @vinz38500 , I will upgrade to this version and Hare tests.

**Comment by trasher** [comment]
Sounds like this issue has been resolved already. Feel free to reopen if problem still persists.
