### ISSUE TITLE
Rendre les dates et profils facultatives

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/news#2]
Bonjour,

Pourrait-on rendre les dates de publication facultatives ?

Si pas de date de début = immédiat.
Si pas de date de fin = infini.

De même le profil devrait être facultatif (pour l'afficher à tout le monde) et fournir d'autres cible (Cf. #1).

Cordialement,
Jérémy

**Comment by ylegrand** [comment]
Je partage cette proposition. Un exemple simple serait une information d'ordre générale, à l'attention de tout les utilisateurs.

**Comment by orthagh** [comment]
Done in 0.90-1.3
