### ISSUE TITLE
[1.3.2.3] It is not displayed on the main page

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/news#26]
no notification is displayed on the main page in version 1.3.2.3

**Comment by Armin83** [comment]
I got message on "main" page after login but not on login page.

**Comment by trasher** [comment]
Maybe related to https://github.com/pluginsGLPI/news/blob/master/setup.php#L32 ?

**Comment by Armin83** [comment]
Sorry i don't unterstand your help.
Should i delete this line ? I have exactly this line.

![img_024](https://cloud.githubusercontent.com/assets/19192087/21387037/0f8ad45c-c776-11e6-8c65-85e8712253e6.jpg)
![img_025](https://cloud.githubusercontent.com/assets/19192087/21387038/0fcccf60-c776-11e6-8a8f-92d0d2eb41ab.jpg)

**Comment by trasher** [comment]
Try replacing:
```
   if (isset($_SESSION['glpiactiveentities_string'])
       && $plugin->isInstalled('news')
       && $plugin->isActivated('news')) {
```
with:
```
   if ($plugin->isInstalled('news')
       && $plugin->isActivated('news')) {
```

**Comment by Armin83** [comment]
Yes - this is working for me.
