### ISSUE TITLE
Alertes non prises en compte

### ISSUE THREAD

**Issue by MaxG89** [pluginsGLPI/news#3]
Bonjour, 

Tout d'abord félicitation pour tous les plugins développés sur GLPI. Ils apportent vraiment un plus à l'appli et facilite énormément le travail :).

Je rencontre toutefois une erreur lors de la création d'une alerte via le menu Alertes. Celle-ci n'est pas enregistrée et n’apparaît pas non plus sur la page d’accueil des utilisateurs sélectionnés? Je reproduit systématiquement quelque soit l'alerte créée.

Merci d'avance.

Version GLPI : 0.85.4
Version Plugin : 0.90-1.0

**Comment by neeftarah** [comment]
Bonjour,

Pouvez-vous nous en dire un peu plus ? Je ne reproduit pas ce problème sur mon poste...

- Passez en mode "debug" (Profil Super-Admin" > Mes préférences > Utiliser GLPI en Mode "Debug"
- Un message d'erreur s'affiche t-il lors de l'enregistrement de l'alerte ? Si oui, lequel ?
- Y a-t-il des choses dans le fichier glpi/files/logs/php-error.log concernant ce plugin ? Idem pour mysql-error.log ?
- Avez-vous d'autres plugins d'installer ? Si oui, lesquels ?

Merci de votre retour,

Cordialement,
Jérémy

**Comment by MaxG89** [comment]
Bonjour et merci pour votre retour.

En mode Debug je n’ai aucun message d’erreur.  

Lorsque je clique sur Ajouter je reviens seulement sur un Nouvel élément – Alertes vide. Si je clique sur l’onglet Alertes il n’y a Pas d’élément trouvé ce qui me fait penser que l’enregistrement ne se fait pas.

Au niveau des Plugins installés on retrouve les suivants :
news                Name: Alertes                        Version: 0.90-1.0   State: Enabled
talk                 	Name: Discussions                 Version: 0.85-1.1   State: Enabled
formcreator     	Name: Formulaires                 Version: 0.85-1.2.4 State: Enabled
mreporting       Name: Plus de rapports          Version: 0.85+1.0   State: Enabled
timezones        Name: Timezones                  Version: 1.2.0      State: Not installed

J’ai également fais une modification du thème de base via le «plugin» Bootstrap theme for GLPI 0.85.4.

Avec les autres Plugins je n’ai aucun problème d’affichage ou de fonctionnement pour le moment.

Concernant les logs (il y'en a un peu) ramenant sur le plugin News vous les trouverez ci-dessous (PHP et SQL).

Merci pour tout.

Bien cordialement.
Maxime

-	Php-errors
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 12:00:27 [@WIN-PGATL30QT08]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 12:00:27 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 12:00:27 [@WIN-PGATL30QT08]
  *** PHP Warning(2): array_keys() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    array_keys()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 12:00:27 [@WIN-PGATL30QT08]
  *** PHP Warning(2): implode(): Invalid arguments passed
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:107    implode()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 13:41:47 [2@WIN-PGATL30QT08]
  *** PHP Warning(2): unlink(D:\w3-GLPI/files/_tmp/remove.txt): Permission denied
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-17 15:56:20 [@WIN-PGATL30QT08]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-17 15:56:20 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-17 15:56:20 [@WIN-PGATL30QT08]
  *** PHP Warning(2): array_keys() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    array_keys()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-17 15:56:20 [@WIN-PGATL30QT08]
  *** PHP Warning(2): implode(): Invalid arguments passed
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:107    implode()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** PHP Warning(2): array_keys() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    array_keys()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** PHP Warning(2): implode(): Invalid arguments passed
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:107    implode()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:44:17 [10@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: classname
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:10:13 [@WIN-PGATL30QT08]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:10:13 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:10:13 [@WIN-PGATL30QT08]
  *** PHP Warning(2): array_keys() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    array_keys()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:10:13 [@WIN-PGATL30QT08]
  *** PHP Warning(2): implode(): Invalid arguments passed
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:107    implode()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:11:46 [2@WIN-PGATL30QT08]
  *** PHP Warning(2): imap_open(): Couldn't open stream {imap.gmail.com:995/imap/ssl/novalidate-cert/notls}
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 16:10:14 [@WIN-PGATL30QT08]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:88     
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 16:10:14 [@WIN-PGATL30QT08]
  *** PHP Notice(8): Undefined index: glpiprofiles
  Backtrace :
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 16:10:14 [@WIN-PGATL30QT08]
  *** PHP Warning(2): array_keys() expects parameter 1 to be array, null given
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:100    array_keys()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 16:10:14 [@WIN-PGATL30QT08]
  *** PHP Warning(2): implode(): Invalid arguments passed
  Backtrace :
  :                                                  
  D:\w3-GLPI\plugins\news\inc\alert.class.php:107    implode()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-19 08:34:03 [2@WIN-PGATL30QT08]
  *** PHP Warning(2): unlink(D:\w3-GLPI/locales/ar_SA.mo): Permission denied


-	SQL errors

  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'1\',\'Adresse email\',\'&lt;p style=\\\"text-align: center;\\\"&gt;&lt;span style=\\\"color: #ff0000;\\\"&gt;&lt;strong&gt;Afin de recevoir la totalité des notifications liées à vos tickets&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;\\r\\n&lt;p style=\\\"text-align: center;\\\"&gt;&lt;span style=\\\"color: #ff0000;\\\"&gt;&lt;strong&gt;pensez à maintenir l\\\'adresse email enregistrée dans votre profil (&lt;em&gt;Mes préférences&lt;/em&gt;) à jour&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;\',\'2015-08-13\',\'2025-08-31\',\'8\',\'2015-08-14 11:10:55\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-14 11:11:49 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'1\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-13\',\'2015-08-28\',\'4\',\'2015-08-14 11:11:48\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-14 11:14:14 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'1\',\'AZERTY\',\'&lt;p&gt;AZERT&lt;/p&gt;\',\'2015-08-13\',\'2015-08-28\',\'4\',\'2015-08-14 11:14:14\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-14 11:19:35 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'0\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-13\',\'2016-08-11\',\'4\',\'2015-08-14 11:19:35\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-14 11:48:37 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_news_alerts` WHERE 
         `is_deleted` = 0
         AND ( DATE(NOW()) BETWEEN `date_start` AND `date_end` )
         AND `profiles_id` IN ()
      
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5
  Backtrace :
  D:\w3-GLPI\inc\commondbtm.class.php:251            
  D:\w3-GLPI\plugins\news\inc\alert.class.php:108    CommonDBTM->find()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-14 13:38:02 [14@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'3\',\'1\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-13\',\'2025-08-16\',\'8\',\'2015-08-14 13:38:02\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-14 16:09:58 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_news_alerts` WHERE 
         `is_deleted` = 0
         AND ( DATE(NOW()) BETWEEN `date_start` AND `date_end` )
         AND `profiles_id` IN ()
      
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5
  Backtrace :
  D:\w3-GLPI\inc\commondbtm.class.php:251            
  D:\w3-GLPI\plugins\news\inc\alert.class.php:108    CommonDBTM->find()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 13:22:58 [@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_news_alerts` WHERE 
         `is_deleted` = 0
         AND ( DATE(NOW()) BETWEEN `date_start` AND `date_end` )
         AND `profiles_id` IN ()
      
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5
  Backtrace :
  D:\w3-GLPI\inc\commondbtm.class.php:251            
  D:\w3-GLPI\plugins\news\inc\alert.class.php:108    CommonDBTM->find()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 15:10:13 [@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_news_alerts` WHERE 
         `is_deleted` = 0
         AND ( DATE(NOW()) BETWEEN `date_start` AND `date_end` )
         AND `profiles_id` IN ()
      
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5
  Backtrace :
  D:\w3-GLPI\inc\commondbtm.class.php:251            
  D:\w3-GLPI\plugins\news\inc\alert.class.php:108    CommonDBTM->find()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-18 16:10:14 [@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_news_alerts` WHERE 
         `is_deleted` = 0
         AND ( DATE(NOW()) BETWEEN `date_start` AND `date_end` )
         AND `profiles_id` IN ()
      
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 5
  Backtrace :
  D:\w3-GLPI\inc\commondbtm.class.php:251            
  D:\w3-GLPI\plugins\news\inc\alert.class.php:108    CommonDBTM->find()
  D:\w3-GLPI\plugins\news\scripts\alert.php:29       PluginNewsAlert::findAllToNotify()
2015-08-19 08:32:04 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'1\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-18\',\'2015-08-18\',\'4\',\'2015-08-19 08:32:04\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-19 08:32:29 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'0\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-18\',\'2015-08-28\',\'4\',\'2015-08-19 08:32:29\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
2015-08-19 08:36:03 [2@WIN-PGATL30QT08]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_plugin_news_alerts` (`entities_id`,`is_recursive`,`name`,`message`,`date_start`,`date_end`,`profiles_id`,`date_mod`) VALUES (\'0\',\'0\',\'TEST\',\'&lt;p&gt;TEST&lt;/p&gt;\',\'2015-08-18\',\'2015-08-26\',\'4\',\'2015-08-19 08:36:03\')
  Error: Field 'is_deleted' doesn't have a default value
  Backtrace :
  inc\commondbtm.class.php:421                       
  inc\commondbtm.class.php:820                       CommonDBTM->addToDB()
  plugins\news\front\alert.form.php:38               CommonDBTM->add()
