### ISSUE TITLE
Alert create permissions

### ISSUE THREAD

**Issue by oliveira0501** [pluginsGLPI/news#35]
Hi,

I'm trying to restrict access to create alert for profiles, is it possible?

Regards,
Oliveira, José

**Comment by Armin83** [comment]
yes - you can select the target profile

**Comment by cedric-anne** [comment]
As @Armin83 says, you can defines targets for alerts.
To customize targets:
1. Go to `Tools > Alerts` page.
2. Open an alert form by clicking on it.
3. Go inside the `Targets` tab.
4. Remove the default `All Profiles` visibility and add a new target corresponding to your needs.
