### ISSUE TITLE
target "All profils" can't be removed

### ISSUE THREAD

**Issue by Miminoux** [pluginsGLPI/news#37]
Hi,

Thanks a lot for the plugin, it fits sooooo good my needs. But I may have found a bug ^^. 

I created a new alert, it automaticly added a target : "Profile - All" in the target tab.
Then I added one profile target, worked fine.
Then I tried to remove the "Profile - all" target which did not work. It resulted in a privilege error (I'm fully admin but working in a specific entity) and the target is still present.
In the database, the targets for that new are the 2 profiles targets which ids are 11 (the profile I added manually) and -1 (the automaticly added at creation). If I drop that -1 target entry from DB, it works fine.

Let me know if I can help.

Thomas

**Comment by flegastelois** [comment]
Hi @Miminoux

Do you have the right "Administration> Entity> Delete permanently" in your profile?
This one is necessary to allow you to delete an alert.

Regards,

**Comment by Miminoux** [comment]
Oh gosh you are right.

My bad ^^
