### ISSUE TITLE
Gestion des profils non pris en compte

### ISSUE THREAD

**Issue by ropie** [pluginsGLPI/news#4]
J'ai un soucis avec les profils.

Je suis en glpi0.85.5 et alertes en 0.90-1.0.

Je créé mon alerte puis je choisi un profil.

2 questions:
- On en peut choisir qu'un seul profil?
- Malgrès le fait que j'ai mis Profil: Self-Service, tous les autres profils voient eux aussi l'alerte, ce qui ne devrait pas être le cas? 

Merci

**Comment by wawax** [comment]
Bonjour, 

Merci de remonter cela directement sur le projet github du plugin. 

Cordialement, 

----- Mail original -----

De: "ropie" <notifications@github.com> 
À: "pluginsGLPI/news" <news@noreply.github.com> 
Envoyé: Mardi 29 Septembre 2015 17:20:35 
Objet: [news] Gestion des profils non pris en compte (#4) 



J'ai un soucis avec les profils. 

Je suis en glpi0.85.5 et alertes en 0.90-1.0. 

Je créé mon alerte puis je choisi un profil. 

2 questions: 

    * On en peut choisir qu'un seul profil? -Malgrès le fait que j'ai mis Profil: Self-Service, tous les autres profiles voient eux aussi l'alerte, ce qui ne devrait pas être le cas? 



Merci 

— 
Reply to this email directly or view it on GitHub . 




-- 


Walid Nouh 
Directeur R&D 

wnouh@teclib.com 

TECLIB' Montpellier 
3 rue Doria, 
34000 Montpellier, France 

Tel. +33 1 79 97 02 78 - Ligne directe : +33 1 79 97 72 93 - Fax. +33 1 72 70 31 18 
Facebook | Twitter | www.teclib.com

**Comment by ropie** [comment]
Je suis bien sur le Github :)
