### ISSUE TITLE
news 1.3.3 - This version require GLPI 9.2 

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/news#45]
**GLPI 9.2 compatible** is not perfect ;)

1.3.3 This version requires GLPi >= 9.2 (not compatible with GLPi 9.1)
would be better again

my version GLPI 9.1.6 Copyright (C) 2015-2017 Teclib' and c

**Comment by AircraftRu** [comment]
This version only for GLPI 9.2. Use 1.3.2.5 version.

**Comment by Armin83** [comment]
I know - but the release nodes could be better in this case. 1.3.4 is better ;)
