### ISSUE TITLE
external view don't work with iframe - display on a separate webpage

### ISSUE THREAD

**Issue by Armin83** [pluginsGLPI/news#46]
Hi,

i want to use the /var/www/glpi/plugins/news/front/external.php for our intranet website but i can't insert this in a iframe. i got this error: this content cannot be displayed in a frame

![img_019](https://user-images.githubusercontent.com/19192087/31881299-677926c4-b7e3-11e7-91d6-023648260373.jpg)

maybe it is this 
`<WebPartPages:AllowFraming runat="server"  />`

http://sharepointpals.com/post/The-Content-cannot-be-displayed-in-a-frame-Display-another-SharePoint-WebApplication-inside-an-iFrame-of-our-SharePoint-Site

or this
`<meta http-equiv="X-Frame-Options" content="allow">`

https://stackoverflow.com/questions/14141388/iframe-this-content-cannot-be-displayed-in-a-frame
but i don't no so much about html - how to change / solve this problem ?

**Comment by cedric-anne** [comment]
Hi,

It requires too much work to add it inside GLPI code. A simplier solution is to make your webserver add `X-Frame-Options` when serving this file. This article can help you https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/X-Frame-Options .

**Comment by Armin83** [comment]
I created a .htaccess file and changed the rules. thanks for your help
```
/plugins/news/front# cat .htaccess
<Files ~ "^\.(htaccess|htpasswd)$">
deny from all
</Files>
<Files hidden_alerts.php>
Header unset X-Frame-Options
</Files>

<Files external.php>
Header unset X-Frame-Options
</Files>

Options -Indexes

#Header unset X-FRAME-OPTIONS
order deny,allow


# If you have problem with session.auto_start on install you need to set this value to 0 on php.ini or uncomment this line
#php_value session.auto_start 0
#Header unset X-FRAME-OPTIONS


# The following lines enable the apache rewriting for the api. You can use url like http://glpi/api/.
#<IfModule mod_rewrite.c>
#   RewriteEngine On
#   RewriteCond %{REQUEST_FILENAME} !-f
#   RewriteCond %{REQUEST_FILENAME} !-d
#   RewriteRule api/(.*)$ apirest.php/$1
#</IfModule>


# You can uncomment following lines to enable caching of web assets (pictures, javascript files, etc)
#<IfModule mod_expires.c>
#   ExpiresActive On
#   ExpiresByType image/jpg "access 1 year"
#   ExpiresByType image/jpeg "access 1 year"
#   ExpiresByType image/gif "access 1 year"
#   ExpiresByType image/png "access 1 year"
#   ExpiresByType text/css "access 1 year"
#   ExpiresByType text/x-javascript "access 1 year"
#   ExpiresByType text/javascript "access 1 year"
#   ExpiresByType application/javascript "access 1 year"
#</IfModule>

```
```
