### ISSUE TITLE
Unable to select date on create / update form

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/news#49]
When i want to delte or create news, calendar buton are not visible.

![selection_046](https://user-images.githubusercontent.com/7335054/34818645-b9d7eca4-f6bb-11e7-87f7-5d25abe6698a.png)

In console mode on chrome i see that the tinyMCE lib is not loaded propery

![selection_047](https://user-images.githubusercontent.com/7335054/34818656-c3645384-f6bb-11e7-886c-c950ef87d912.png)

If i reload page, the buton are displayed.

**Comment by cedric-anne** [comment]
This problem should be solved by https://github.com/pluginsGLPI/news/commit/54b2acf7688bfc897d9bc47f8896a15b5eff07ac .
