### ISSUE TITLE
News : 1.3.5 : Bug

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/news#62]
Using Chrome and IE, a big text shown on **connexion screen**  can't scroll up or down (not integer)
The same text on the main screen (after log on) is integer.

The text contains about 30 lines.

**Comment by stonebuzz** [comment]
Hi @EC2311 

can you test this PR -> https://github.com/pluginsGLPI/news/pull/73/files

Which add scrollbar if needed

Best regards

**Comment by EC2311** [comment]
Hello

Thanks for your attention.

I am now in 1.5.4 ;) 

your test seems not to change anything

I force the value max-height into 100px, but no effect?

.plugin_news_alert-login .expanded .plugin_news_alert-content {
   padding: 5px 15px;
   max-height: 100px;
   Overflow-y:auto;
   transition: max-height .25s ease-in;
   transition: padding .25s ease-in;
}

I did 'ctrl F5' to force cache..

**Comment by stonebuzz** [comment]
Hi @EC2311 
Can you activate debug mode and retry to relod css cache.

Best regards

**Comment by EC2311** [comment]
Hello

After activating the debug : No information about "result debug" visible on the main page. 

Below an example I get : 
![image](https://user-images.githubusercontent.com/42341169/73246058-fbed4500-41ad-11ea-800d-891e444978ef.png)

in spite of style.css updated : 
![image](https://user-images.githubusercontent.com/42341169/73246103-17585000-41ae-11ea-8c70-4f00a6d742e4.png)

**Comment by stonebuzz** [comment]
Hi @EC2311 

Be careful, your overflow directive have upper case -> **O**verflow-y

its overflow-y.

Best regards

**Comment by EC2311** [comment]
Hi, 

I have the same result :(

about the debug mode : it's on, but as the problem appears on logon screen : how can we see something in debug ?
![image](https://user-images.githubusercontent.com/42341169/73258053-2f879980-41c5-11ea-9ad0-2ead3e553f1e.png)

![image](https://user-images.githubusercontent.com/42341169/73258010-1f6fba00-41c5-11ea-883a-bca2428138e0.png)

**Comment by stonebuzz** [comment]
Hi @EC2311 

can you remove all files in /glpi/files/_cahce/

and retry (to force glpi to regenerate scss files from css.

Best regards

**Comment by EC2311** [comment]
I deleted all files in glpi/files/_cache
![image](https://user-images.githubusercontent.com/42341169/73264778-d8d58c00-41d3-11ea-9d93-50ccaae4616a.png)

and....
Same result

![image](https://user-images.githubusercontent.com/42341169/73264824-f0ad1000-41d3-11ea-9907-fc3f3ac777e7.png)
always no lift on the window (chrome navigator)

**Comment by stonebuzz** [comment]
Can toi change overflow-y by overflow, empty cache folder and retry with debug mode enable ?

Best regards

**Comment by EC2311** [comment]
in fact, I succeeded :)

the update must be done not in styles.css but in styles.min.css !

I found that by setting Chrome in debug, and look the source
![image](https://user-images.githubusercontent.com/42341169/73267081-96627e00-41d8-11ea-88da-39da538e06e8.png)

result : 
![image](https://user-images.githubusercontent.com/42341169/73267044-7e8afa00-41d8-11ea-9774-54f902e9bbe3.png)

**Comment by stonebuzz** [comment]
have you used "overflow" directive or "overflow-y" ?

Best regards

**Comment by EC2311** [comment]
**overflow-y : auto;**

here is the line it-self : 
plugin_news_alert-login .expanded .plugin_news_alert-content{padding:5px 15px;max-height:500px;overflow-y : auto;transition:max-height .25s ease-in;transition:padding .25s ease-in}

**Comment by stonebuzz** [comment]
thanks.

Best regards
