### ISSUE TITLE
 Text on the login page does not expand - v 1.6.0

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/news#79]
Hello

I'm using GLPI with version 9.4.5 and News in 1.6.0. However, on the login page the message does not expand. can you help me?

![erro](https://user-images.githubusercontent.com/35368369/77752354-27ea4280-7006-11ea-87e2-10c9e1568617.gif)

**Comment by phamorais** [comment]
Any?

**Comment by stonebuzz** [comment]
Hi @phamorais 

I'm not reproduce your problem,
which plugin have you use to change login page background and login form ?

Best regards

**Comment by phamorais** [comment]
@stonebuzz 
Hello, I didn't use any plugin, I customized the index and css. But analyzing it I found that some add-ons were missing, and it was not a bug in the plugin. I've already managed to fix it. You can close this issue.

**Comment by phamorais** [comment]
Closed.
