### ISSUE TITLE
When "vertical split" layout is selected then "Save" button is not visible in tickets

### ISSUE THREAD

**Issue by grajek** [pluginsGLPI/news#9]
GLPI 0.90.1, 0.90.2, Alerts 0.90-1.0

1. "vertical split" layout is selected,
2. News is more than one line.

=  "Save" button is not visible in tickets (see screenshot).

![glpi_news_example](https://cloud.githubusercontent.com/assets/539507/14425424/78928762-ffe7-11e5-9b5d-55e4d2bb4f58.png)

**Comment by orthagh** [comment]
version 0.90-1.3 should fix this issue
